/*
 * Copyright 2025 the original author or authors
 *
 * SPDX-License-Identifier: MIT
 */

package net.nmoncho.sbt.dependencycheck
package settings

import scala.jdk.CollectionConverters._

import org.owasp.dependencycheck.dependency.Dependency
import org.owasp.dependencycheck.dependency.Vulnerability
import org.owasp.dependencycheck.utils.SeverityUtil
import sbt.Logger

/** Trait used to define how Summaries are generated after an analysis
  */
trait SummaryReport {

  /** Builds an analysis summary using the scanned dependencies and the build-failure policy
    *
    * @param dependencies scanned dependencies
    * @param policy       policy deciding which vulnerabilities fail the build
    * @return
    */
  def buildSummary(dependencies: Seq[Dependency], policy: FailurePolicy): String

}

object SummaryReport {

  private final val NewLine = System.getProperty("line.separator", "\n").intern()

  /** Shows the summary to the console
    *
    * @param name          project name
    * @param dependencies  scanned dependencies
    * @param policy        policy deciding which vulnerabilities fail the build
    * @param report        report type
    * @param log           logger
    */
  def showSummary(
      name: String,
      dependencies: Seq[Dependency],
      policy: FailurePolicy,
      report: SummaryReport
  )(
      implicit log: Logger
  ): Unit = {
    val summary = report.buildSummary(dependencies, policy)

    log.warn(
      s"\n\nOne or more dependencies were identified with known vulnerabilities in [$name]:\n\n${summary}" +
        "\n\nSee the dependency-check report for more details.\n\n"
    )
  }

  /** Processes a vulnerability to include in a report
    *
    * If it's a failing vulnerability, it will output the line in yellow.
    *
    * @param v vulnerability to report
    * @param policy policy deciding which vulnerabilities fail the build
    * @return vulnerability report line
    */
  private def processVulnerability(v: Vulnerability, policy: FailurePolicy): String = {
    val score = Seq(
      Option(v.getCvssV2).map(s => s"CVSSv2 ${s.getCvssData.getBaseScore}"),
      Option(v.getCvssV3).map(s => s"CVSSv3 ${s.getCvssData.getBaseScore}"),
      Option(v.getCvssV4).map(s => s"CVSSv4 ${s.getCvssData.getBaseScore}"),
      Option(v.getUnscoredSeverity).map(s =>
        s"Unscored (estimated) ${SeverityUtil.estimateCvssV2(s)}"
      )
    ).flatten.mkString(", ")

    if (policy.isFailing(v)) {
      s"${scala.Console.YELLOW}${v.getName()}${scala.Console.RESET} (${scala.Console.YELLOW}${score}${scala.Console.RESET})"
    } else {
      s"${v.getName()} (${score})"
    }
  }

  /** Processes dependencies to be included in the report
    *
    * @param dependencies        scanned dependencies
    * @param reportVulnerability predicate to define if a [[Vulnerability]] should be shown or not in the summary
    * @param summary             [[StringBuilder]] used for aggregating the report
    */
  private def dependencyProcessor(
      dependencies: Seq[Dependency],
      reportVulnerability: (Vulnerability, FailurePolicy) => Boolean,
      policy: FailurePolicy,
      summary: StringBuilder
  ): Unit =
    dependencies.foreach { dependency =>
      if (!dependency.getVulnerabilities.isEmpty) {
        val formattedVulnerabilities =
          dependency
            .getVulnerabilities(true)
            .asScala
            .collect {
              case v if reportVulnerability(v, policy) =>
                processVulnerability(v, policy)
            }

        if (formattedVulnerabilities.nonEmpty) {
          summary
            .append(dependency.getFileName)
            .append(": ")

          summary.append(
            formattedVulnerabilities.mkString(", ")
          )

          summary.append(NewLine)
        }
      }
    }

  /** Original summary generated by Owasp DependencyCheck
    *
    * See [[org.owasp.dependencycheck.agent.DependencyCheckScanAgent.showSummary]]
    */
  object Original extends SummaryReport {

    override def buildSummary(dependencies: Seq[Dependency], policy: FailurePolicy): String = {
      val summary = StringBuilder.newBuilder

      dependencies.foreach { d =>
        val ids = d.getVulnerabilities(true).asScala.map(_.getName).mkString(", ")

        if (ids.nonEmpty) {
          summary.append(d.getFileName).append("( ")
          summary.append(
            (d.getSoftwareIdentifiers.asScala ++ d.getVulnerableSoftwareIdentifiers.asScala)
              .map(_.getValue)
              .mkString(", ")
          )
          summary.append("): ").append(ids).append(NewLine)
        }
      }

      summary.toString()
    }

  }

  /** Shows all vulnerabilities in the summary with their corresponding score, whether they are an
    * offending vulnerability or not.
    */
  object AllVulnerabilities extends SummaryReport {

    override def buildSummary(dependencies: Seq[Dependency], policy: FailurePolicy): String = {
      val summary = StringBuilder.newBuilder

      dependencyProcessor(dependencies, (_, _) => true, policy, summary)

      summary.toString()
    }

  }

  /** Shows only offending vulnerabilities in the summary with their corresponding score.
    */
  object OffendingVulnerabilities extends SummaryReport {

    override def buildSummary(dependencies: Seq[Dependency], policy: FailurePolicy): String = {
      val summary = StringBuilder.newBuilder

      dependencyProcessor(
        dependencies,
        (v, p) => p.isFailing(v),
        policy,
        summary
      )

      summary.toString()
    }

  }

}
