name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  LOG_LEVEL: INFO
  DATA_DIRECTORY: cve-data/
  CI: true
  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Check formatting, scalafix, and headers
        run: sbt styleCheck

      - name: Restore CVE Database
        id: restore-cve-db
        uses: actions/cache@v4
        with:
          path: cve-data/
          key: cve-data

      - name: Test Coverage
        run: sbt test

      - name: Test SBT
        run: sbt scripted

      - name: Save CVE Database
        id: save-cve-db
        uses: actions/cache/save@v4
        if: always()
        with:
          path: cve-data/
          key: cve-data
